### ISSUE TITLE
Change user details from the admin interface

### ISSUE THREAD

**Issue by frafra** [apache/incubator-answer#346]
**Is your feature request related to a problem? Please describe.**
It would be nice to change username, email, activation status (active/inactive) from the admin interface.

**Describe the solution you'd like**
Allow administrators to change users' details by visiting their profiles or add new button to the users' dropdown of the users' table in the admin interface, to change the other values.

**Describe alternatives you've considered**
I am editing the database manually at the moment. It works, but it is not very user-friendly.

**Comment by fenbox** [comment]
Thank you for your suggestion.

Currently, the admin can only modify the status. We will improve this in the future.

**Comment by carlqt** [comment]
Hi. Is there any progress on this issue or can I help out?

**Comment by fenbox** [comment]
> Allow administrators to change users' details by visiting their profiles to change the other values.

I like this solution.

## Description

The route `/users/settings/*` needs to be changed to `/users/{{ username }}/settings/*`.

**Admin, Moderator** can see user's "Edit profile" button. Click to change user's details.

![image](https://github.com/answerdev/answer/assets/360618/931fb6ee-4e10-4fd6-9dd1-29312644fd2a)

**Permissions:** 

- Can change:
  - `/users/{{ username }}/settings/profile`
  - `/users/{{ username }}/settings/notifications`
  - `/users/{{ username }}/settings/interface`
- Can not change (because the user's current password is required):
  - `/users/{{ username }}/settings/account`

| Role | Moderator | Admin |
|--------|--------|--------|
| Change User's settings | Allow | Allow |
| Change Moderator's settings | - | Allow |
| Change Admin's settings | - | Allow |

**Comment by fenbox** [comment]
@carlqt We would be very thankful if you could help with [this](https://github.com/answerdev/answer/issues/346#issuecomment-1717117813).

**Comment by carlqt** [comment]
@fenbox Cool. Sorry for the late reply. Yeah, I'd like to help on this.

I'll return to this thread a bit later. I will try to create a simple pseudocode on how I will solve this and see if that's the expectation that you all have.

**Comment by fenbox** [comment]
@carlqt Hi Carl, how is the progress going?

**Comment by jihuayu** [comment]
> Admin, Moderator can see user's "Edit profile" button. Click to change user's details.

@fenbox I have a small question: Why does a moderator need the ability to modify user settings? Moderators should be the ones managing forum content such as questions and tags, and in theory, they shouldn't have a need to modify user settings. Modifying user settings should be considered the responsibility of a system administrator, shouldn't it?

I think modifying user settings is a strange requirement, and I find it difficult to envision its use cases. For example, the boss asked us to turn off his email notifications?
I think we can ask @frafra in which specific scenarios they require administrators to modify user settings.

**Comment by fenbox** [comment]
Hi @carlqt, as @jinhuayu said, we need more information before we start making changes.

**Comment by carlqt** [comment]
Hey guys I'm really sorry. I've been busy and wasn't able to work on this

**Comment by fenbox** [comment]
@carlqt It's okay. Others will follow up.
