### ISSUE TITLE
[Development] make ui exits due to linting error

### ISSUE THREAD

**Issue by khamui** [apache/incubator-answer#431]
**Describe the bug**
Running `make ui` exits with a linting error.

**To Reproduce**
1. Run `make ui` to install frontend locally for development
2. It will exit due to column length (80)

**Expected behavior**
Should install frontend 

**Screenshots**
-

**Platform (please complete the following information):**
 - Device: [e.g. Desktop, Mobile]
 - OS: [e.g. macOS]

**Comment by khamui** [comment]
Do you want me to push my fix? I would like to contribute :)

**Comment by shuashuai** [comment]
> Do you want me to push my fix? I would like to contribute :)

We welcome all forms of contributions and look forward to your PRs!

**Comment by AdityaMayukhSom** [comment]
I cannot reproduce this issue on my local system using `make ui`. I have tried in both `dev` and in `main` branch.
If this issue has been resolved, please mark this as closed and if possible, please add a link to the PR. 

Also running `make ui` modifies the `pnpm-lock.yaml` file automatically. I am not sure if this is the expected behavior, or if the lock file should not be versioned.
