### ISSUE TITLE
mysql connection database failed

### ISSUE THREAD

**Issue by maxbad** [apache/incubator-answer#634]
The image I am using is answerdev/answer:1.2.0, with a MySQL database. Everything works fine except when the server is restarted, I encounter the following error: "Connection to the database failed: dial tcp 172.18.0.2:3306: connect: connection refused." However, the container starts running normally immediately after restarting it.

config.yaml
```
debug: false
server:
  http:
    addr: 0.0.0.0:80
data:
  database:
    driver: mysql
    connection: answer:test123@tcp(mysql:3306)/answer
  cache:
    file_path: /data/cache/cache.db
i18n:
  bundle_dir: /data/i18n
service_config:
  upload_path: /data/uploads
swaggerui:
  show: false
  protocol: http
  host: 127.0.0.1
  address: :80
```

**Comment by kumfo** [comment]
May I ask if this situation can be reproduced every time?

**Comment by Sunlineroom** [comment]
try to set it mode for Sqlite

**Comment by hhhguany** [comment]
I have identified the issue. Due to the `mysql` server restarting under certain circumstances, I suspect that after the restart process fails to connect to the database, the `answer` service will not continue to retry connecting to the database. Therefore, even after my `mysql` server has completed the restart, accessing the answer service still results in the error "HTTP Error 50X The server encountered an error and could not complete your request." 

The issue differs from #472 as the error does not manifest at the start of the service, however, the underlying logic error seems similar. To maintain service availability, it is essential to implement a reconnection operation to address potential database disconnections (e.g. the network connection interruption) during service running.
