### ISSUE TITLE
React Frontend - Issue with being progressive web app. Adding 12 seconds latency

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#809]
## Describe the bug

It looks Entire JS code getting dumped in one JS file. That loading is synchronous / blocking next level of fetches. 

It adds 12 seconds of additional latency. That's pretty bad for user experience.

This is for my site where I am not using any CDN.
![image](https://github.com/apache/incubator-answer/assets/9161543/4754bb90-b8f8-4c03-9032-e2b1f2068662)

### Screenshots

If applicable, add screenshots or video to help explain your problem.

### Platform

- Device: [e.g. Desktop, Mobile]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.2.0]

**Comment by surapuramakhil** [comment]
@fenbox Ah, it's actually a bug. React is a progressive web App. This feature comes out of the box for almost all major front-end frameworks like Vue, angular, svelte not just React. Unless configurations are messed or explicitly disabled, this won't be the case.

This could be transitive effect of this https://github.com/apache/incubator-answer/issues/784

**Comment by shuashuai** [comment]
First of all, this is due to the packaging method of create-react-app. CRA will package all used node_modules packages into main.js; and main.js will return to the seat entry file to load the page and display the functions within the page，main.js will be used as the entry file of the application to load the page and display the functions within the page. All core logic is completed in main.js。

Secondly, React is a JavaScript library for rendering user interfaces (UI) rather than a progressive web App,  of course you can use CRA to build PWA applications.

Finally, the real core of the problem here is that main.js is indeed a bit large. If the user does not enable http caching, or the network conditions are not good, it will cause the file to take too long to load,in response to this situation,I will split main.js in one of the next releases, so please be patient.

**Comment by surapuramakhil** [comment]
@shuashuai No, I am not on Slow 3G (that's related to throttling feature of Edge stimulate running on slow internet). My internet speeds are actually over 150 MBPS.

My internet speed results
![image](https://github.com/apache/incubator-answer/assets/9161543/8b95f5a5-5f18-41ae-a354-3f09f573c227)

**Comment by shuashuai** [comment]
> @shuashuai No, I am not on Slow 3G (that's related to throttling feature of Edge stimulate running on slow internet). My internet speeds are actually over 150 MBPS.
> 
> My internet speed results ![image](https://private-user-images.githubusercontent.com/9161543/309616797-8b95f5a5-5f18-41ae-a354-3f09f573c227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjMyNjQsIm5iZiI6MTcwOTUyMjk2NCwicGF0aCI6Ii85MTYxNTQzLzMwOTYxNjc5Ny04Yjk1ZjVhNS01ZjE4LTQxYWUtYTM1NC0zZjA5ZjU3M2MyMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDMyOTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTgzNDhhYTZkNjhiYzAwZjc0ODlhMDlhYmNkNGZjM2MwZmIzYWUxYjM0YmRkMTJlMzdmMzE3YWRiYzhlODAyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Pdf8-XK0ynillks2Sg3vJ3H3lY89BRmHMQuBpNPv2uM)

I saw it from your screenshot

![image](https://github.com/apache/incubator-answer/assets/30591202/44377207-fe96-48fe-8a70-844c92020422)

**Comment by surapuramakhil** [comment]
I understood "why you said that". It's a stimulation (DevTools feature of Microsoft Edge) 

and coming to this
> I will split main.js

I would recommend exploring other build tools. Checkout other popular react projects on GitHub.
Apache Superset uses "webpack" https://github.com/apache/superset/blob/master/superset-frontend/package.json
freeCodeCamp uses "getsBy" https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/package.json
