### ISSUE TITLE
Gamification: Contribution Streak

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#889]
## Is your feature request related to a problem? Please describe

A topics Streak feature (well known from Snapchat).

Streak continues if user performs contribution/activity.

- Upvote / Downvote
- Post Question
- Post Answer

This can be considered as optional:
- comment & emoji reaction https://github.com/apache/incubator-answer/issues/883

**Comment by fenbox** [comment]
The key point of Answer is to generate valuable content through interaction.

While Streak can promote interaction, it may lead to sending a large amount of content without careful consideration in order to generate more interaction, resulting in a decline in information quality.

We should focus more on the value generated through knowledge sharing and collaboration, rather than individual achievements.
