### ISSUE TITLE
Issue with reading the Search engines meta verifications tags

### ISSUE THREAD

**Issue by Kiwifu** [apache/incubator-answer#895]
## Describe the bug

Issue with reading the Search engines meta verifications tags

### Expected behavior

 I Have issue with getting confirmed by most known search engines like : Google, Bing or even Yandex.

I tried to add the verification code Head tags, but it's not working, the verifications are impossible and not recognized as it is not detectable.

Can you please check what is the issue?

- Version: [e.g. v1.3.0]

**Comment by shuashuai** [comment]
This problem is because the code currently inserted through the CSS/HTML customization feature is inserted during client-side rendering, so search engines cannot crawl directly to this customized content.

To resolve this issue, we will add these customizations in the SEO template files in version 1.3.6.
